:PROPERTIES:
:UNNUMBERED: t
:END:
#+title: Mail Database Project
#+AUTHOR: Christian Johnson\and&\and Dan Nusraty\and&\and Dylan Mcgill\and\newline Optimail
#+LATEX_HEADER: \usepackage{tabularx}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage{tikz-uml}
#+EXPORT_FILE_NAME: Project03
#+OPTIONS: toc:nil
#+begin_export latex
\newpage
#+end_export
* Main Entities
- User (Mailroom Employee)
- Package
- Database
- Database Tables
- Application/System
- Email
- Cadet


* Attributes
** User
- Username
- Password
- Access Priviledge
** Package
- Tracking Number
- Addressee
- Address
** Database
- Name
- Filepath
- Sqlite3 Connection
- Sqlite3 Cursor
- Tables
** Table
- Properties
- Name
** Email
- Addressee
- Subject
- Content
** System
- GUI state
- User
** Cadet
- Name
- Email
- Box Number
- Graduation Date

* Relationships
A single database will contain several tables.
A single table will contain several Cadets.
A single table will contain several packages.
A single table will contain several users.
A single cadet can be associated with several packages.
A single cadet can receive several emails.
A single package can be associated with several emails.
A single application can be associated with several users.
A single application is associated with at least 3 database tables.

* Constraints
???


* Domain Model

#+begin_export latex
\begin{tikzpicture}
  \umlclass[x=-3,y=-4]{User}{
    - Username : string \\
    - Password : string \\
    - AccessPrivilege : string
  }{}

  \umlclass[x=1,y=-8]{Package}{
    - TrackingNumber : string \\
    - Addressee : string \\
    - Address : string
  }{}

  \umlclass[x=6,y=0]{Database}{
    - Name : string \\
    - Filepath : string \\
    - SQLite3Connection \\
    - SQLite3Cursor \\
    - Tables
  }{}

  \umlclass[x=6,y=-4]{Table}{
    - Properties : string \\
    - Name : string \\
  }{}

  \umlclass[x=-3,y=-13]{Email}{
    - Addressee : string \\
    - Subject : string \\
    - Content : string
  }{}

  \umlclass[x=-3,y=0]{Application}{
    - GUIState : string \\
    - User
  }{}

  \umlclass[x=6,y=-13]{Cadet}{
    - Name : string \\
    - Email : string \\
    - BoxNumber : string \\
    - GraduationDate : date \\
  }{}


 \umlassoc[mult1=1, pos1=0.2, mult2=*, pos2=0.9]{Database}{Table}
 \umlassoc[mult1=1, pos1=0.1, mult2=1, pos2=0.9]{Application}{Database}
 \umlassoc[mult1=1, pos1=0.3, mult2=*, pos2=0.9]{Application}{User}
 \umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{Table}{User}
 \umlassoc[mult1=1, pos1=0.3, mult2=*, pos2=0.9]{Table}{Package}
 \umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{Table}{Cadet}
 \umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{Cadet}{Package}
 \umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{Cadet}{Email}
 \umlassoc[mult1=1, pos1=0.3, mult2=1..*, pos2=0.9]{Package}{Email}

  %\umlassoc[mult1=*, pos1=0.1, mult2=1, pos2=0.9]{Database}{Table}
  %\umlassoc[mult1=*, pos1=0.1, mult2=*, pos2=0.9]{Table}{Cadet}
  %\umlassoc[mult1=*, pos1=0.1, mult2=*, pos2=0.9]{Table}{Package}
  %\umlassoc[mult1=*, pos1=0.1, mult2=*, pos2=0.9]{Table}{User}
  %\umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{Cadet}{Package}
  %\umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{Cadet}{Email}
  %\umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{Package}{Email}
  %\umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{System}{User}
  %\umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{System}{Database}
  %\umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{System}{Table}
\end{tikzpicture}
#+end_export


* Class Diagram

#+begin_export latex
\begin{tikzpicture}
  \umlclass[x=-5,y=-6]{User}{
    - Username : string \\
    - Password : string \\
    - AccessPrivilege : string
  }{
    + Login(Username, Password) \\
    + Logout()
  }

  \umlclass[x=1,y=-10.5]{Package}{
    - TrackingNumber : string \\
    - Addressee : string \\
    - Address : string
  }{}

  \umlclass[x=3,y=0]{Database}{
    - Name : string \\
    - Filepath : string \\
    - SQLite3Connection \\
    - SQLite3Cursor \\
    - Tables
  }{
    + AddUser(Username, Password, AccessPriviledge) \\
    + AddPackage(BoxNumber, TrackingNumber) \\
    + SearchPackages(CadetName, BoxNumber, TrackingNumber)
  }

  \umlclass[x=4,y=-6]{Table}{
    - Properties : string \\
    - Name : string \\
  }{
    + AddEntry(key, value) \\
    + RemoveEntry(key, value) \\
    + SearchEntries(fields, query, return)
  }

  \umlclass[x=-6,y=-13]{Email}{
    - Addressee : string \\
    - Subject : string \\
    - Content : string
  }{
    + Send()
  }

  \umlclass[x=-5,y=0]{Application}{
    - GUIState : string \\
    - User
  }{
    + Open()
  }

  \umlclass[x=4,y=-15]{Cadet}{
    - Name : string \\
    - Email : string \\
    - BoxNumber : string \\
    - GraduationDate : date \\
  }{}


 \umlaggreg[mult1=1, pos1=0.2, mult2=*, pos2=0.7]{Database}{Table}
 \umlassoc[mult1=1, pos1=0.1, mult2=1, pos2=0.9]{Application}{Database}
 \umlassoc[mult1=1, pos1=0.3, mult2=*, pos2=0.9]{Application}{User}
 \umlaggreg[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{Table}{User}
 \umlaggreg[mult1=1, pos1=0.3, mult2=*, pos2=0.9]{Table}{Package}
 \umlaggreg[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{Table}{Cadet}
 \umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.7]{Cadet}{Package}
 \umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{Cadet}{Email}
 \umlassoc[mult1=1, pos1=0.3, mult2=1..*, pos2=0.6]{Package}{Email}

  %\umlassoc[mult1=*, pos1=0.1, mult2=1, pos2=0.9]{Database}{Table}
  %\umlassoc[mult1=*, pos1=0.1, mult2=*, pos2=0.9]{Table}{Cadet}
  %\umlassoc[mult1=*, pos1=0.1, mult2=*, pos2=0.9]{Table}{Package}
  %\umlassoc[mult1=*, pos1=0.1, mult2=*, pos2=0.9]{Table}{User}
  %\umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{Cadet}{Package}
  %\umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{Cadet}{Email}
  %\umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{Package}{Email}
  %\umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{System}{User}
  %\umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{System}{Database}
  %\umlassoc[mult1=1, pos1=0.1, mult2=*, pos2=0.9]{System}{Table}
\end{tikzpicture}
#+end_export
