:PROPERTIES:
:UNNUMBERED: t
:END:
#+title: Mail Database Project
#+OPTIONS: toc:nil
#+AUTHOR: Christian Johnson\and&\and Dan Nusraty\and&\and Dylan McGill\and\newline Optimail
#+begin_export latex
\newpage
#+end_export

* Preface
Tasks taken to complete this assignment:
- Compiled all code files and class documents to Git repo
- Went over code structure and general function of the system in its current state
- Discussed how best to test various components of the application
- Tested several components of the system
- Fixed issues with application
- Pushed working, fixed code to Github $\newline$
Changelog:
- Tables are more visually appealing
- Added a logout button (currently non-functional)
- Added USCGA logo
- Tables now resize automatically (will shrink if empty, also allows app to fullscreen)z
- Added search capability to Data tab
- Added Delete capability to Data tab
- Added edit button to Data tab, now raises submenu when clicked (main functionality still WIP)


* Test Plan
Testing will be primarily manual, since the majority of our code is focused on a GUI interface.
This will consist of several stages of testing, focused on different sections of the application.

We will begin with test data. Using random name generators and random number generators, we will gather a fictitious data set comprised of no less than 50 entries, compile those entries into a CSV file, and upload the CSV file to our database using our application.

In order to verify that this data uploaded correctly, we will spot-check 5 entries from the terminal, verifying the rest of the entries with the graphical tables in our application.

Next, we will begin examining the GUI components of our application - ensuring first that all navigational components function correctly, then focusing on individual tabs.
For each graphical tab in the interface, each member of the development team will focus, seperately, on the same tab for a period of 1 day, manually checking each function within that tab and verifying the expected result.

* Working Prototype


